# Generated by Django 2.2 on 2022-01-15 00:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
import pols.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Polls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_name', models.CharField(max_length=60, verbose_name='Название')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='дата старта')),
                ('finish_date', models.DateField(default=datetime.date.today, verbose_name='Дата окончания')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10, verbose_name='Имя пользователя')),
                ('Ответы польователя', models.CharField(max_length=200, verbose_name=pols.models.Choice)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('answer_text', models.CharField(max_length=100)),
                ('answer_choices', models.CharField(choices=[('Yes', 'No'), ('Maybe', 'Im not sure')], default=1, max_length=10)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pols.Polls')),
            ],
        ),
    ]
